server {
  server_name ares-protocol.xyz www.ares-protocol.xyz;
  root /var/www/landing;
  index index.html;

  location = /docs {
    return 301 /docs/;
  }

  location /docs/ {
    alias /var/www/ares/ares-protocol/docs/;
    index index.html;
    try_files $uri $uri/ /docs/index.html;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
