[profile.default]
src = "core"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
